### PR TITLE
Adding containization for the header

### PR DESCRIPTION
**Pull request by VincentBlondeau**
and fix when clicking on the current class in the debugger when the method is defined in a superclass

### CODE REVIEW

**Comment by VincentBlondeau** [comment]
😎

**Comment by girba** [comment]
This one actually introduced a regression as now we the method coder is not selected.

Screenshot 2024-07-15 at 21 55 12

**Comment by girba** [comment]
Opened an issue here: https://github.com/feenkcom/gtoolkit/issues/3900

**Comment by VincentBlondeau** [comment]
Sorry about that.. Thanks Tudor!

**Comment by girba** [comment]
No problem. We fixed it :).

**Pull request merged**
